<?php
include('header.php');
?>

<div class="page">

<section class="row">
	<div class="container">
		<div class="about_bg">
			<h1>Privacy Policy for Mayo Surgical, LLC Users</h1>
<p><strong>IMPORTANT – READ CAREFULLY:</strong>  This policy describes the types of  information Mayo Surgical, LLC, its parent, subsidiaries and affiliate  companies (&quot;Mayo Surgical&quot; or &quot;we&quot;) may collect from you  (&quot;you&quot; or &quot;your&quot;) or that you may provide when you visit  this Website and its related sites (our &quot;Website&quot;) and our practices  for collecting, using, maintaining, protecting and disclosing that  information.  We have posted terms and  conditions that also govern your use of this website.  Use of this website and/or content and/or information  provided or displayed on or through this website may also be subject to license  (ours or others), regulation, and/or other/additional terms and conditions.</p><br />
<p>Please read this policy carefully to understand our policies  and practices regarding your information and how we will treat it. If you do  not agree with our policies and practices, your choice is not to use our website.  By accessing or using this website, you agree to this privacy policy. This  policy may change from time to time.  The  date the privacy policy was last revised is identified at the bottom of this  policy. You are responsible for periodically visiting our website and this  privacy policy to check for any changes. Your continued use of this website  after we make changes is deemed to be acceptance of those changes, so please  check the policy periodically for updates.</p><br />
<p><strong>Information We  Collect About You and How We Collect It</strong><br />
  We respect the right to privacy of all visitors to this  website. We do not seek to collect information that would personally identify  you unless you choose to provide it.  For  example, if you choose to use our forums, applications, web-based or other  electronic services that are accessed or offered through this website, the  privacy policy and terms of use of those sites will apply. The personal  information that you submit via response forms on this website is shared only  with those people (for example, but not limited to, our employees, contractors,  partners, and/or service providers) who need this information to respond to  your question or request.  We may also  collect certain non-identifying information that allows the website to  communicate with your computer or other of your devices during your use of the  website.  We may also track certain  technical elements, such as &ldquo;cookies&rdquo;, Web beacons, Web bugs, pixel tags, and similar  technology, related to your navigation and use of the website for technical  reasons and to allow us to understand and improve the experience of using the  website for our users.  If you object to  this, please refer to your web browser&rsquo;s documentation for information on  erasing or blocking such tracking elements.   Except as described in this policy, we do not save personal information  to use for other purposes, nor do we provide it to any other organizations –  except as may be required to be utilized to address any inappropriate use of  our website or as required by law or court order.</p><br />
<p><strong>Information from  Children</strong><br />
  This website is not intended for use for children under 13  years of age.  No one under age 13 may provide  any information to, through, or on the website.   We do not knowingly collect personal information of children under  13.  If you are under the age of 13, do  not use or provide any information on this website or through any of its  features or applications.</p><br />
<p><strong>Hyperlinks</strong><br />
  This website may contain links to other websites that we do  not own, control, or maintain.  We cannot  be, and are not, responsible for their privacy policies and practices, and we  do not make any representations or warranties about the privacy policies, or  your use, of any website which is linked to or from which you linked to this  website.  We recommend that you read and  understand all policies and terms of use with respect to those other website and  that you contact its operator if you have questions or concerns.</p><br />
<p><strong>Use of and/or Disclosure  of Information</strong><br />
  We may use and/or disclose certain information that we  collect or you provide, as described in this policy:</p>
<ul class="policy_link">
  <li>To our parent, subsidiary, or affiliated  companies</li>
  <li>To a buyer or other successor in the event of a  merger, divestiture, restructuring, reorganization, dissolutions, sale, or  other transfer of some or all of our assets, in which the information held by  and through this website is among the assets being transferred</li>
  <li>To fulfill the purpose for which you provided it  or any other purpose disclosed by us when you provide the information</li>
  <li>With your consent</li>
  <li>To comply with any court order, law or legal  process, including to respond to any government or regulatory request</li>
  <li>If we believe it is necessary or appropriate to  protect the rights, property, or safety of ourselves or others</li>
</ul><br />
<p><strong>Opt Out /  Modification of Information</strong><br />
  If you do not want to be on our mailing list, you can opt  out at the time of sign-up or later by using the unsubscribe feature in the  footer of an email from us.   If you wish  to request removal or modification of your personally identifiable information  provided through this website, you can contact us and we will make reasonable  efforts to accommodate your request, provided you inform us of the context in  which the information was provided to us.</p><br />
<p><strong>Privacy Policy  Updates</strong><br />
  This policy may be updated from time to time in response to  technology, regulatory, or other changes in business conditions or our  operations.  We reserve the right to update  this policy at any time, and in our sole discretion, with or without notice to  you.   This policy was last updated  December 2014.</p><br />
<p><strong>[Your terms of use  should focus on use of the website, but set aside password protected areas that  are gateway/subject to separate terms or license/use   Not good to put everything in the hopper on  your company info site]</strong></p><br />
<p><strong><u>Terms of Use</u></strong><br />
  <strong>IMPORTANT – READ  THESE TERMS AND CONDITIONS CAREFULLY BEFORE USING THIS WEBSITE.  BY ACCESSING OR OTHERWISE USING THIS WEBISTE,  YOU CONSENT TO THE FOLLOWING TERMS AND CONDITIONS.</strong></p><br />
<p>Please also review our [Privacy Policy], which also governs  your visit to our website, to understand our practices. <br />
  Mayo Surgical, LLC, its parent, subsidiaries, and affiliate  companies (collectively, &quot;Mayo Surgical&quot; or &ldquo;We&rdquo;) operates this  website and its derivative sites (collectively, the &quot;Website&quot;) as a  service to its customers, employees, contractors, partners, suppliers, and  others subject to these terms and all modifications thereto. By entering and/or  using this Website, you, the user (&ldquo;User&rdquo;, &quot;you&quot; or  &quot;your&quot;), are deemed to have agreed to comply with and be bound to the  following terms and conditions (&quot;Terms&quot;). If you are not willing to  abide by the Terms, do not use this Website. We reserve the right to modify the  Terms at any time, and without actual notice to you. You should check the Terms  periodically for changes. All such changes to the Terms will appear on this  Website. By entering and/or using this Website following any modifications to  the Terms, you agree to be bound by any such modifications to the Terms. We  reserve the right to expel users and prevent their further access to this  Website in their sole discretion without notice.</p><br />
<p><strong>Copyright Notice</strong><br />
  Copyright © 2014 Mayo Surgical, LLC.  All Rights Reserved.</p><br />
<p><strong>Claims of Copyright  Infringement</strong><br />
  We consider ourselves an online service provider under  Subsection 512(c) of the Digital Millennium Copyright Act, Title 17 of the U.S.  Code and have this notice in place to address claims of copyright infringement  on our internet services. If you believe that material on our Website or  service infringes your copyright, you may submit a notification to us, and by  providing the following information:</p>
<ul class="policy_link">
  <li>The name and contact information of the  complaining party,</li>
  <li>Sufficient information to identify the  copyrighted work or works,</li>
  <li>The allegedly infringing material and its  location on our Website or service,</li>
  <li>A statement by the rights holder that it has a  good faith belief that there is no legal basis for the use of the materials  complained of,</li>
  <li>A statement of the accuracy of the notification  and, under penalty of perjury, that the complaining party is authorized to act  on behalf of the rights holder, and</li>
  <li>The notification must be signed physically or  using an electronic signature by the rights holder or person authorized to act  on behalf of the holder of the exclusive right that is allegedly infringed.</li>
</ul><br />
<p>We will take reasonable steps to identify, and deny access  to our Website or services by, individuals who are repeat offenders of other's  copyrights.</p><br />
<p><strong>Trademark Notice</strong><br />
  The names, marks and logos appearing in this Website are,  unless otherwise noted, trademarks owned by or licensed to Mayo Surgical. The  use of these marks by others, except as provided for in these Terms is prohibited.  From time to time, we make fair use in this Website of trademarks owned and  used by third parties.  Any such marks  are clearly noted, and we make no claim to ownership of those marks.  Unless otherwise noted on the Website, all  trademarks, service marks, and logos used in this Website are the trademarks,  service marks or logos of their respective owners.</p><br />
<p><strong>Intellectual Property  Rights</strong><br />
  The contents of this Website, including, but not limited, to  text, graphics and images are protected by copyright, trademark and other  intellectual property right laws.</p><br />
<p>All content included on this  Website, such as text, graphics, logos, button icons, images, audio clips,  digital downloads, data compilations, and software, is the property of Mayo  Surgical or is licensed to Mayo Surgical and protected by United States and  international copyright laws. The compilation of all content on this site is  the exclusive property of Mayo Surgical, with copyright authorship for this  collection by Mayo Surgical, and protected by U.S. and international copyright  laws.</p><br />
<p><strong>License and Site Access</strong><br />
  Subject at all times and in all  respects to these Terms, we grant you a revocable, non-exclusive,  non-transferable, limited license to view or print the content in this Website  without alterations, for personal, non-commercial use only. This limited  license does not apply to any media or platform other than that of the current  Site; and, further, does not create a business or personal services  relationship between you and Mayo Surgical.   Access to and use of other services from or through this Website may be  subject to other or additional terms and conditions.</p><br />
<p>As between You and Mayo Surgical,  other than any User Posting that You contribute to the Website through forums  or methods that we provide or approve in advance, all Information, data, or  other material, in any form or media, contained in, obtained from, or relating  to the Website, including all results obtained from the Website and any User  Postings (collectively, &ldquo;Content&rdquo;) on the Website is (and shall continue to be)  owned exclusively by us or others, and is protected under applicable  copyrights, patents, trademarks, trade dress, and/or other proprietary rights,  and the copying, redistribution, use or publication by you of any such Content  or any part of the Website is prohibited. Under no circumstances will you  acquire any ownership rights or other interest in any Content by or through  your use of this Website.</p><br />
<p><strong>Restrictions on Use</strong><br />
  You agree not to knowingly: (i) use  any device, software or technique to interfere with or attempt to interfere  with the proper working of the Website; (ii) post or transmit to the Website  any unlawful, fraudulent, harassing, libelous, or obscene Information of any  kind; (iii) post or send to the Website any Information that contains a virus,  bug, or other harmful item; (iv) publish, perform, distribute, prepare  derivative works, copy, reverse engineer, or use the Content (other than as  expressly permitted herein); (v) post or transmit into or on the Website any  Information in violation of another party's copyright or intellectual property  rights; (vi) take any action which imposes an unreasonable or  disproportionately large load on our infrastructure or that of our service  providers; (vii) redeliver any of the Content using &quot;framing&quot;,  hyperlinks, or other technology without our express written permission; or,  (viii) use any device or technology to provide repeated automated attempts to  access password-protected portions of the Website or, (ix) engage in any marketing  or advertising activities, other than with our express consent, or, (x) to  falsely represent your identity on the Website.</p><br />
<p>You acknowledge that we have the  right, but no obligation, to monitor the Website and to disclose any information  necessary to operate the Website, to protect ourselves, others, and our  customers, and to comply with legal obligations or governmental requests. We  reserve the right to refuse to post or to remove any information on the Website,  in whole or in part, for any reason. You agree to comply with all governmental  laws, statutes, ordinances, and regulations (including unfair competition,  anti-discrimination or false advertising) regarding your use of the Website.</p><br />
<p><strong>Certain Website Use by You</strong><br />
  If you are allowed access to  password-protected areas of the Website, you agree to keep your password  confidential, to send notice to us within twenty-four (24) hours if your  password is compromised. You acknowledge that we neither endorse nor are  affiliated with any Website that may link to the Website and are not  responsible for any information that appears on such linked website. You  acknowledge that (i) the internet is a network of computers worldwide, and that  any Information submitted by you to us necessarily is routed via third party  computers to us, (ii) we are not responsible for lapses in online security and  do not assume liability for improper use of your information by a third party.</p><br />
<p><strong>Submissions of Information by You</strong><br />
  If you submit information to  the Website (e.g., in chat rooms or customer ratings and review areas which may  include data, text, software, music, sound, photographs, graphics, video,  messages, or other materials (each, a &quot;User Posting&quot;)., you grant us  an irrevocable, nonexclusive, worldwide, royalty-free license (sub licensable  through multiple tiers) to (in any media now known or not currently known or  invented) link to, utilize, use for any purpose, copy, exploit, and prepare  derivative works of the submitted information. No information you submit shall  be deemed confidential. However, you agree that we may use, process and display  your personally identifiable information in accordance with the terms of our  Privacy Policy.  YOU RETAIN OWNERSHIP OF  ANY COPYRIGHTS OR OTHER INTELLECTUAL PROPERTY RIGHTS APPLICABLE TO ANY  INFORMATION YOU SUBMIT TO US.  You agree  that you are solely responsible for all of your User Postings and understand  that you may not have recourse to edit or remove your User Postings. You  consent to having your personal data transferred to and processed in the United  States. You will release, protect, defend, indemnify and hold harmless Mayo  Surgical, LLC, its parent, subsidiaries and affiliates, its suppliers,  partners, and service providers (of any tier), and the officers, directors,  employees, contractors, and agents of all the foregoing from and against any  legal claim by a third party based upon the content of your User Posting.  By submitting a User Posting, you represent and  warrant that:</p><br />
  <ul class="policy_link">
  <li><strong>a</strong>. you are at least 13 years old;</li>
  <li><strong>b</strong>. you own all rights in your User Postings  (including, without limitation, all rights to the audio, video, or digital  recording and the performance contained in your User Postings) or,  alternatively, you have acquired all necessary rights (including all payment of  any kind arising from the exploitation of the User Posting) in your User  Postings to enable you to grant to us the rights in your User Postings  described herein;</li>
 <li><strong>c</strong>. you are the individual pictured and/or heard in  your User Postings or, alternatively, you have obtained permission from each  person (including consent from parents or guardians for any individual under  the age of eighteen (18)) who appears and/or is heard in your User Postings to  grant the rights to us described herein;</li>
  <li><strong>d</strong>. your User Postings do not infringe the copyright,  trademark, patent, trade secret, or other intellectual property rights, privacy  rights, or any other legal or moral rights of any third party;</li>
  <li><strong>e</strong>. you voluntarily agree to waive all &quot;moral  rights&quot; that you may have in your User Posting;</li>
  <li><strong>f</strong>. any information contained in your User Posting is  not known by you to be false, inaccurate, or misleading;</li>
  <li><strong>g</strong>. your User Posting does not violate any law  (including, but not limited to, those governing export control, consumer  protection, unfair competition, anti-discrimination, or false advertising);</li>
  <li><strong>h</strong>. your User Posting is not, and may not reasonably  be considered to be, defamatory, libelous, hateful, racially, ethnically,  religiously, or otherwise biased or offensive, unlawfully threatening, or  unlawfully harassing to any individual, partnership, or corporation, vulgar,  pornographic, obscene, or invasive of another&rsquo;s privacy;</li>
  <li><strong>i</strong>. you were not and will not be compensated or  granted any consideration by any third party for submitting your User Posting;</li>
  <li><strong>j</strong>. your User Posting does not incorporate materials  from a third party web site, or addresses, email addresses, contact  information, or phone numbers (other than your own);</li>
  <li><strong>k</strong>. your User Posting does not contain any viruses,  worms, spyware, adware, or other potentially damaging programs or files;</li>
  <li><strong>l</strong>. your User Posting does not contain any information  that you consider confidential, proprietary, or personal; and</li>
  <li><strong>m</strong>. your User Posting does not contain or constitute  any unsolicited or unauthorized advertising, promotional materials, junk mail,  spam, chain letters, pyramid schemes, or any other form of solicitation.</li>
  </ul><br />
<p><strong>Applicability and Cooperation</strong><br />
  We reserve the right to limit the  provision of any product or service to any person, geographic area, or  jurisdiction as we so desire, or as required by law.  We, in our sole and absolute discretion, may  add, delete, or change the Content of this Website at any time, without notice  to you.  You acknowledge and agree to  comply with all U.S. laws, regulations and requirements applicable to the use  of this Website, and, as applicable, to the export of U.S. origin products and  technology.</p><br />
<p><strong>LIMITED WARRANTY AND DISCLAIMER</strong><br />
  NO REPRESENTATION IS MADE ABOUT THE  SUITABILITY OF THE CONTENT HEREON. THIS WEBSITE, AND ACCESS TO ANY LINKED SITE,  IS PROVIDED TO YOU BY ALL CONTENT PROVIDERS, INCLUDING US, &quot;AS-IS&quot;  AND &quot;AS-AVAILABLE&quot;, WITH NO REPRESENTATIONS OR WARRANTIES OF ANY  KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES  OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, AND  NON-INFRINGEMENT. YOU HEREBY DISCLAIM ALL WARRANTIES BY US RELATING TO YOUR USE  OF THE WEBSITE. YOU ACKNOWLEDGE THAT YOUR ACCESS TO THE WEBSITE WILL NOT BE  FREE OF INTERRUPTIONS, THAT THE INFORMATION HEREIN, AND THE OPERATION OF THE  WEBSITE, MAY CONTAIN BUGS, ERRORS, VIRUSES OR OTHER HARMFUL MATERIALS, TECHNICAL  INACCURACIES, PROBLEMS OR OTHER LIMITATIONS, AND THAT THE WEBSITE MAY BE  UNAVAILABLE FROM TIME TO TIME. YOU ASSUME TOTAL RESPONSIBILITY AND RISK FOR  YOUR USE OF THE WEBSITE AND WEBSITE-RELATED SERVICES.  IF YOUR USE OF THE WEBSITE OR CONTENT RESULTS  IN ANY COSTS OR EXPENSES, INCLUDING, WITHOUT LIMITATION, THE NEED FOR SERVICING  OR REPLACING EQUIPMENT OR DATA, WE WILL NOT BE LIABLE FOR THOSE COSTS OR  EXPENSES.</p><br />
<p><strong>LIMITATION OF LIABILITY</strong><br />
  WE WILL NOT BE LIABLE FOR DAMAGES  OF ANY KIND, WHETHER ACTUAL, PUNITIVE, INCIDENTAL OR CONSEQUENTIAL (INCLUDING  DAMAGES FROM LOSS OF BUSINESS, LOST PROFITS, LITIGATION, OR THE LIKE), ARISING  OUT OF OR IN CONNECTION WITH THIS WEBSITE OR ANY CONTENT ON OR ACCESSED THROUGH  THIS WEBSITE, OR ANY WEBSITE LINKED TO, OR ANY COPYING, DISPLAYING OR USE  THEREOF, THE UNAVAILABILITY OF THIS WEBSITE, DAMAGE TO YOUR COMPUTER, OR ANY  LOSS OF DATA OR BUSINESS INTERRUPTION RESULTING FROM THE USE OF THIS WEBSITE,  WHETHER OR NOT SUCH DAMAGES ARE FORESEEABLE OR IN CONTEMPLATION OF THE PARTIES,  EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, AND WITHOUT  REGARD TO THE FORM OF ACTION AND WHETHER IN CONTRACT, TORT, NEGLIGENCE, STRICT  LIABILITY, OR OTHERWISE.</p><br />
<p>IF YOU ARE DISSATISFIED WITH ANY  PORTION OF THIS WEBSITE, THE CONTENTS OF THE WEBSITE, OR WITH ANY OF THESE  TERMS, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USING THE WEBSITE.</p><br />
<p>THE NEGATION OF DAMAGES SET FORTH  ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN YOU AND MAYO  SURGICAL.  THE WEBSITE AND THE  INFORMATION AND CONTENT THEREIN WOULD NOT BE PROVIDED WITHOUT SUCH  LIMITATIONS.  NO ADVICE OR INFORMATION,  WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM US THROUGH THE SITE SHALL CREATE  ANY WARRANTY, REPRESENTATION OR GUARANTEE NOT EXPRESSLY STATED IN THIS  AGREEMENT.</p>
<p>Certain state laws do not allow  limitations on implied warranties or the exclusion or limitation of certain damages.  If these laws apply to you, some or all of the above disclaimers, exclusions,  or limitations may not apply to you, and you might have additional rights.</p><br />
<p><strong>Indemnity</strong><br />
  You agree to indemnify, hold  harmless and defend Mayo Surgical, its parent, subsidiaries, and affiliates,  its and their respective officers, directors, employees, contractors (of any  tier), and agents from and against any and all losses, claims, damages, demand,  cause of action, debt, loss or liability, including reasonable attorneys' fees  and accounting fees that we may become obligated to pay arising or resulting  from your use of the Website and contents therein, or your breach of these  Terms. We further reserve the right to assume or participate, at your expense,  in the investigation, settlement and defense of any such action or claim.</p><br />
<p><strong>User's Remedy</strong><br />
  If you are dissatisfied with any  portion of this Website or with any of these Terms, your sole and exclusive  remedy is to discontinue using this Website.</p><br />
<p><strong>Applicable Law and Jurisdiction</strong><br />
  By accessing or visiting this  Website, you expressly agree that the laws of the State of Georgia, excluding  its conflict of laws principles, shall govern these Terms. You further agree  and expressly consent to the exercise of personal jurisdiction in the courts of  the State of Georgia in connection with any such dispute and including any  claim involving Mayo Surgical or its telecommunication providers and Content  providers. If federal jurisdiction exists over any action, suit or proceeding  arising out of or in any way connected with any claim involving Mayo Surgical,  you agree that the United States District Court for the Northern District of Georgia  has exclusive jurisdiction. When federal jurisdiction does not exist over that  action, suit or proceeding, you and Mayo Surgical designate the courts of  Fulton County, Georgia, for the exclusive venue and resolution of that dispute  and submit to the jurisdiction of that court.</p><br />
<p>If any provision is found to be  invalid by any court having competent jurisdiction, the invalidity of such  provision shall not affect the validity of the remaining provisions of these  Terms, which shall remain in full force and effect. No waiver of any of these  Terms shall be deemed a further or continuing waiver of such term or any other  term. Other than as expressly provided elsewhere in our Website, these Terms  constitute the entire agreement between you and us with respect to your use of  this Website.</p><br />
<p>Any cause of action you may have  with respect to your use of the Website must be commenced within one (1) year  after the claim or cause of action arises.</p>
        </div>	
	</div>
</section>

</div>
<?php
require($get_footer);
?>
