<?php
echo $path = $_SERVER['DOCUMENT_ROOT']."/path.php";
echo require_once($path);
echo include($config);
$functions = $_SERVER['DOCUMENT_ROOT']."/classes/functions.php";
require_once($functions);
$getinformation = new Allfunctions();
echo $user_id = $_POST['id'];
$query = mysql_query("UPDATE `members` set `activated`='1' where `id` = '$user_id'");
$user_email_id = $getinformation->GetObjectById($user_id,"email_id");
$designation = $getinformation->GetObjectById($user_id,"designation");
if($designation==1 || $designation==2 || $designation==3 || $designation==4 || $designation==6 || $designation==7)
{
	$subject = "Welcome to Mayo Surgical";
	$message = "Your Account is Activated";
	$extravalues = array("Welcome"=>"Welcome to Mayo Surgical. For On-line Update please Logged In your Account for further Updates","Note"=>"This is the Autogenerated Email. Please Don't Reply");
	$getinformation->SendEmail($user_email_id,$subject,$message,$extravalues);
}
echo "Updated";
?>
